version: "3.7"

networks:
  dbnet:
    driver: bridge
    ipam:
      config:
       - subnet: 10.5.0.0/16
       
services:  
    zoo1:
        image: zookeeper:3.4.14
        restart: always
        hostname: zoo1
        container_name: zoo1
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
        networks: 
            dbnet:
                ipv4_address: 10.5.0.21

    zoo2:
        image: zookeeper:3.4.14
        restart: always
        hostname: zoo2
        container_name: zoo2
        ports:
            - 2182:2181
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
        networks: 
            dbnet:
                ipv4_address: 10.5.0.22

    zoo3:
        image: zookeeper:3.4.14
        restart: always
        hostname: zoo3
        container_name: zoo3
        ports:
            - 2183:2181
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
        networks: 
            dbnet:
                ipv4_address: 10.5.0.23